planner:
  ros__parameters:
    plan_solver_plugins: ["POPF"]
    POPF:
      plugin: "plansys2/POPFPlanSolver"
    TFD:
      plugin: "plansys2/TFDPlanSolver"

executor:
  ros__parameters:
    action_timeouts:
      actions: []
